import '@/app/globals.css'
import AppHeader from '@/components/AppHeader'
import SessionProvider from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

export const metadata = {
  title: 'Blog | Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico'
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <AppHeader />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
