import '@/app/globals.css'
import AppHeader from '@/components/AppHeader'

export const metadata = {
  title: 'Blog | Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        {children}
      </body>
    </html>
  )
}
